9p2/Controllers/proController.cs
using _9p2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _9p2.Controllers
{
    public class proController : Controller
    {
        private readonly mydb db;
        private readonly  IWebHostEnvironment env;
        public proController(mydb db, IWebHostEnvironment env)
        {
            this.db = db;
            this.env = env;
        }
        public IActionResult Index()
        {
          var a=  db.products.Include(a => a.category).ToList();
            return View(a);
        }
        public IActionResult add()
        {
            ViewBag.data = new SelectList(db.categories, "cat_id", "cat_name");
            return View();
        }
        [HttpPost]
        public IActionResult add(product p,IFormFile pro_image)
        {
            ViewBag.data = new SelectList(db.categories, "cat_id", "cat_name");
            string pa = Path.Combine(env.WebRootPath, "images", Path.GetFileName(pro_image.FileName));
            pro_image.CopyTo(new FileStream(pa, FileMode.Create));
            p.pro_image = pro_image.FileName;
            db.products.Add(p);
            db.SaveChanges();
            ModelState.Clear();
            return View();
        }
        public IActionResult edit(int id)
        {
            var prod =db.products.Find(id);
            return View(prod);
        }
        [HttpPost]
        public IActionResult edit(product e, int id)
        {
            var prod = db.products.Find(id);
            prod.pro_name = e.pro_name;
            prod.price = e.price;
            prod.qty = e.qty;
            prod.categorycat_id = e.categorycat_id;
            prod.pro_image = e.pro_image;
            return RedirectToAction("Index");
        }
        public IActionResult delete(int id)
        {
            var del=db.products.Find(id);
            db.products.Remove(del);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

9p2/Views/pro/Index.cshtml
@model List<product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/master.cshtml";
}

<div class="card">
    <div class="card-header">
        <h1 class="card-title">Products List</h1>
        <a asp-controller="pro" asp-action="add" class="btn btn-primary float-right">Add Product</a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.pro_id</td>
                        <td>@item.pro_name</td>
                        <td>@item.qty</td>
                        <td>@item.price</td>
                        <td><img src="~/images/@item.pro_image" width="60" height="60"></td>
                        <td>@item.category.cat_name</td>
                        <td>
                            <a asp-controller="pro" asp-action="edit" asp-route-id="@item.pro_id"><i class="fa-solid fa-pencil mr-5" style="color:darkgreen"></i></a>
                            <a asp-controller="pro" asp-action="delete" asp-route-id="@item.pro_id"><i class="fa-solid fa-trash-can" style="color:red"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
          @*   <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Action</th>
                </tr>
            </tfoot> *@
        </table>
    </div>
    <!-- /.card-body -->
</div>

9p2/Views/pro/add.cshtml
@model product
@{
    ViewData["Title"] = "add";
    Layout = "~/Views/Shared/master.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Add New Category</h3>
        <a asp-controller="pro" asp-action="index" class="btn btn-danger float-right">Back</a>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-controller="pro" asp-action="add" method="post" enctype="multipart/form-data">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Product Name</label>
                <input asp-for="pro_name" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Product Name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Price</label>
                <input asp-for="price" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Price">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Quantity</label>
                <input asp-for="qty" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Quantity">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <select class="form-control" asp-for="categorycat_id" asp-items="ViewBag.data">  </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Quantity</label>
                <input asp-for="pro_image" type="file" class="form-control" id="exampleInputEmail1" placeholder="Select Image">
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

9p2/Views/pro/edit.cshtml
@model product
@{
    ViewData["Title"] = "edit";
    Layout = "~/Views/Shared/master.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Edit Category</h3>
        <a asp-controller="pro" asp-action="index" class="btn btn-danger float-right">Back</a>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-controller="pro" asp-action="edit" method="post" enctype="multipart/form-data">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Product Name</label>
                <input asp-for="pro_name" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Product Name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Price</label>
                <input asp-for="price" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Price">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Quantity</label>
                <input asp-for="qty" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Quantity">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <select class="form-control" asp-for="categorycat_id" asp-items="ViewBag.data">  </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Image</label>
                <input asp-for="pro_image" type="file" class="form-control" id="exampleInputEmail1" placeholder="Select Image">
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
    </form>
</div>