9p2/Controllers/adminController.cs
using _9p2.Models;
using Microsoft.AspNetCore.Mvc;

namespace _9p2.Controllers
{
    public class adminController : Controller
    {
        private readonly mydb db;
        public adminController(mydb db)
        {
            this.db = db;
        }
        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult login(tbl_login l)
        {
           var check= db.logins.Where(a=>a.login_email== l.login_email && a.login_pass==l.login_pass).FirstOrDefault();
            if (check != null)
            {
                HttpContext.Session.SetString("username",check.login_name.ToString());
                return RedirectToAction("dashboard");
            }
            else
            {
                ViewBag.msg="Login Failed";
            }
            return View();
        }

        public IActionResult dashboard()
        {
            if (HttpContext.Session.GetString("username") ==null)
            {
                return RedirectToAction("login");
            }
            return View();
        }
        public IActionResult logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("login");
        }
    }
}

9p2/Views/admin/login.cshtml
@model tbl_login
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlib/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/adminlib/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlib/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form asp-controller="admin"asp-action="login" method="post">
                    <div class="input-group mb-3">
                        <input asp-for="login_email" type="email" class="form-control" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input asp-for="login_pass" type="password" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">
                                    Remember Me
                                </label>
                            </div>
                        </div>
                        @ViewBag.msg
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <div class="social-auth-links text-center mb-3">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-primary">
                        <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                    </a>
                    <a href="#" class="btn btn-block btn-danger">
                        <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                    </a>
                </div>
                <!-- /.social-auth-links -->

                <p class="mb-1">
                    <a href="forgot-password.html">I forgot my password</a>
                </p>
                <p class="mb-0">
                    <a href="register.html" class="text-center">Register a new membership</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/adminlib/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/adminlib/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlib/dist/js/adminlte.min.js"></script>
</body>
</html>