9p2/Controllers/catController.cs
using _9p2.Models;
using Microsoft.AspNetCore.Mvc;

namespace _9p2.Controllers
{
    public class catController : Controller
    {
        private readonly mydb db;
        public catController(mydb db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
           var a= db.categories.ToList();
            return View(a);
        }
        public IActionResult add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult add(category c)
        {
           var check = db.categories.Where(a => a.cat_name == c.cat_name).FirstOrDefault();
            if (check != null)
            {
                ViewBag.msg = "Category is already available!";
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.categories.Add(c);
                    db.SaveChanges();
                    ModelState.Clear();
                }
            }

            return RedirectToAction("index");
        }
        public IActionResult edit(int id)
        {
            var change =db.categories.Find(id);
            return View(change);
        }
        [HttpPost]
        public IActionResult edit(category e, int id)
        {
            var row =db.categories.Find(id);
            row.cat_name = e.cat_name;
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public IActionResult delete(int id)
        {
            var del = db.categories.Find(id);
            db.categories.Remove(del);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

9p2/Views/cat/Index.cshtml
@model List<category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/master.cshtml";
}

<div class="card">
    <div class="card-header">
        <h1 class="card-title">Categories List</h1>
        <a asp-controller="cat" asp-action="add" class="btn btn-primary float-right">Add Category</a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Category Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
               @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.cat_id</td>
                        <td>@item.cat_name</td>
                        <td>
                            <a asp-controller="cat" asp-action="edit" asp-route-id="@item.cat_id"><i class="fa-solid fa-pencil mr-5" style="color:darkgreen"></i></a>
                            <a asp-controller="cat" asp-action="delete" asp-route-id="@item.cat_id"><i class="fa-solid fa-trash-can" style="color:red"></i></a>
                            </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Category Name</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>

9p2/Views/cat/add.cshtml
@model category
@{
    ViewData["Title"] = "add";
    Layout = "~/Views/Shared/master.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Add New Category</h3>
        <a asp-controller="cat" asp-action="index" class="btn btn-danger float-right">Back</a>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-controller="cat" asp-action="add" method="post">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input asp-for="cat_name" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Category">
            </div>
            <span style="color:red">@ViewBag.msg</span>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

9p2/Views/cat/edit.cshtml
@model category
@{
    ViewData["Title"] = "edit";
    Layout = "~/Views/Shared/master.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Edit Category</h3>
        <a asp-controller="cat" asp-action="index" class="btn btn-danger float-right">Back</a>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-controller="cat" asp-action="edit" method="post">
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input asp-for="cat_name" type="Name" class="form-control" id="exampleInputEmail1" placeholder="Enter Category">
            </div>
            <span style="color:red">@ViewBag.msg</span>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
    </form>
</div>